doublestar: true
formatter:
  disable_alias_key_correction: true
  eof_newline: true
  indent: 2
  indentless_arrays: true
  line_ending: lf
  retain_line_breaks_single: true
  retain_line_breaks: true
  trim_trailing_whitespace: true
